name: MSBuild

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  APPX_CERTIFICATE_PASSWORD: ${{secrets.APPX_CERTIFICATE_PASSWORD}}

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build solution
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: python build.py --target=build --config=debug --platform=x64 --ci-certificate=FedoraWSL-Appx-Test.pfx
